# Generated by Django 5.1.7 on 2025-07-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(help_text='Unique identifier for the QR code (e.g., DK001)', max_length=20, unique=True)),
                ('link', models.URLField(help_text='The URL encoded in the QR code', max_length=500)),
                ('message', models.TextField(blank=True, help_text='The message associated with the QR code, entered by the user', null=True)),
                ('qr_image', models.ImageField(blank=True, help_text='The generated QR code image file', null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Code Data',
                'verbose_name_plural': 'QR Code Data',
                'ordering': ['unique_key'],
            },
        ),
    ]
