# Generated by Django 5.2.4 on 2025-07-24 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_qrcodedata_attached_image_qrcodedata_background_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='message_data',
            field=models.JSONField(blank=True, help_text='JSON data containing text elements, positions, styles, and background info from the message editor', null=True),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Legacy: Optional attached image', null=True, upload_to='message_images/'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('gradient', 'Gradient'), ('image', 'Image')], default='gradient', help_text='Type of background: color, gradient, or image', max_length=10),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='background_value',
            field=models.TextField(blank=True, default='linear-gradient(45deg, #ff9a9e, #fecfef)', help_text='Background value: hex color, CSS gradient, or base64 image data'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='message',
            field=models.TextField(blank=True, help_text='Legacy: Simple text message', null=True),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Legacy: Hex code for simple text color', max_length=7),
        ),
        migrations.CreateModel(
            name='MessageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The text content')),
                ('x_position', models.FloatField(help_text='X position as percentage (0-100)')),
                ('y_position', models.FloatField(help_text='Y position as percentage (0-100)')),
                ('font_size', models.IntegerField(default=24, help_text='Font size in pixels')),
                ('font_family', models.CharField(default='Inter', help_text='Font family name', max_length=100)),
                ('color', models.CharField(default='#ffffff', help_text='Text color hex code', max_length=7)),
                ('font_weight', models.CharField(default='normal', help_text='Font weight (normal, bold)', max_length=20)),
                ('font_style', models.CharField(default='normal', help_text='Font style (normal, italic)', max_length=20)),
                ('text_decoration', models.CharField(default='none', help_text='Text decoration (none, underline)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_elements', to='qr_app.qrcodedata')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
