# Generated by Django 5.2.4 on 2025-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_qrcodedata_message_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodedata',
            name='message_data',
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Optional: An image to be displayed *inside* the message box with the text.', null=True, upload_to='message_images/'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', help_text="Choose 'color' for a solid background or 'image' for a background image.", max_length=10),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='background_value',
            field=models.CharField(blank=True, default='#fff8e1', help_text="For 'color', enter a hex code (e.g., #FFFFFF). For 'image', enter a URL or path to the image.", max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='message',
            field=models.TextField(blank=True, help_text='The message associated with the QR code, entered by the user', null=True),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='text_color',
            field=models.CharField(default='#4a2c2a', help_text='Hex code for the message text color (e.g., #RRGGBB)', max_length=7),
        ),
        migrations.DeleteModel(
            name='MessageElement',
        ),
    ]
