# Generated by Django 5.2.4 on 2025-07-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_remove_qrcodedata_message_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodedata',
            options={},
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='attached_image',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='background_type',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='background_value',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='link',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='message',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='qr_image',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='unique_key',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='composited/'),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='text_blocks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
