# Generated by Django 5.2.4 on 2025-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_alter_qrcodedata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodedata',
            options={'ordering': ['unique_key'], 'verbose_name': 'QR Code Data', 'verbose_name_plural': 'QR Code Data'},
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='image',
        ),
        migrations.RemoveField(
            model_name='qrcodedata',
            name='text_blocks',
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Optional: An image to be displayed *inside* the message box with the text.', null=True, upload_to='message_images/'),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='background_type',
            field=models.CharField(choices=[('color', 'Color'), ('image', 'Image')], default='color', help_text="Choose 'color' for a solid background or 'image' for a background image.", max_length=10),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='background_value',
            field=models.CharField(blank=True, default='#fff8e1', help_text="For 'color', enter a hex code (e.g., #FFFFFF). For 'image', enter a URL or path to the image.", max_length=255),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='link',
            field=models.URLField(help_text='The URL encoded in the QR code', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='message',
            field=models.TextField(blank=True, help_text='The message associated with the QR code, entered by the user', null=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='The generated QR code image file', null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='text_color',
            field=models.CharField(default='#4a2c2a', help_text='Hex code for the message text color (e.g., #RRGGBB)', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='unique_key',
            field=models.CharField(help_text='Unique identifier for the QR code (e.g., DK001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
