# Generated by Django 5.2.4 on 2025-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0006_alter_qrcodedata_options_remove_qrcodedata_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodedata',
            options={'ordering': ['-updated_at', 'unique_key'], 'verbose_name': 'QR Code Data', 'verbose_name_plural': 'QR Code Data'},
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='font_family',
            field=models.CharField(choices=[('Lora', 'Lora'), ('Montserrat', 'Montserrat'), ('Pacifico', 'Pacifico'), ('Caveat', 'Caveat')], default='Lora', help_text='Font family for the message text', max_length=50),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='font_size',
            field=models.IntegerField(default=24, help_text='Font size in pixels (12-48)'),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='text_position_x',
            field=models.FloatField(default=50.0, help_text='Horizontal position of text as percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='text_position_y',
            field=models.FloatField(default=50.0, help_text='Vertical position of text as percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='attached_image',
            field=models.ImageField(blank=True, help_text='Composite image containing background and positioned text overlay', null=True, upload_to='message_images/'),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='background_value',
            field=models.CharField(blank=True, default='#f0f0f0', help_text="For 'color', enter a hex code. For 'image', enter a URL or path.", max_length=255),
        ),
        migrations.AlterField(
            model_name='qrcodedata',
            name='text_color',
            field=models.CharField(default='#333333', help_text='Hex code for the message text color (e.g., #333333)', max_length=7),
        ),
    ]
